# Generated by Django 5.1.1 on 2024-10-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_student_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='age',
            field=models.TextField(default='18', max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='instructors/licenses/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/profile_pics/'),
        ),
    ]
