# Generated by Django 5.1.1 on 2024-10-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_classschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='sunday_time',
        ),
    ]
