# Generated by Django 5.1.1 on 2024-10-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_classschedule_sunday_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classschedule',
            old_name='friday_time',
            new_name='friday_end',
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='monday_time',
            new_name='friday_start',
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='saturday_time',
            new_name='monday_end',
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='thursday_time',
            new_name='monday_start',
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='tuesday_time',
            new_name='saturday_end',
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='wednesday_time',
            new_name='saturday_start',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='thursday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='thursday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='tuesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='tuesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='wednesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='wednesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
