# Generated by Django 5.1.1 on 2024-10-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_classschedule_friday_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/profile_pics/'),
        ),
        migrations.AddField(
            model_name='student',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='instructors/licenses/'),
        ),
    ]
