# Generated by Django 5.1.1 on 2024-10-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_student_proof_feedbackstaff_feedbackstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstaff',
            old_name='staff',
            new_name='instructor',
        ),
    ]
